kind: pipeline
name: Publish_to_NPM
type: docker

trigger:
  event:
    - tag

steps:
- name: publish
  image: node:alpine
  environment:
    NPM_ACCESS_TOKEN:
      from_secret: NPM_ACCESS_TOKEN
  commands:
  - npm set //registry.npmjs.org/:_authToken $NPM_ACCESS_TOKEN
  - npm publish

---

kind: pipeline
name: Publish_to_DockerHub
type: docker

environment:
  IMAGE_NAME: aliyun-ddns-updater

trigger:
  event:
  - tag
  - cron

steps:
- name: prepare
  image: docker:19
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - docker pull node:alpine
- name: build
  image: docker:19
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - docker build -t $IMAGE_NAME .
- name: push
  image: docker:19
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  environment:
    DOCKERHUB_USERNAME:
      from_secret: DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD:
      from_secret: DOCKERHUB_PASSWORD
  commands:
  - docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME
  # - docker rmi $IMAGE_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME # Cache can be reused.

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
